### ISSUE TITLE
Inscription site https://sill.etalab.gouv.fr/ : problème de majuscules

### ISSUE THREAD

**Issue by ThierryM** [etalab/sill#1]
Bonjour,

Je vous fais remonter un petit problème lorsqu'on s'inscrit sur le site https://sill.etalab.gouv.fr/. En effet, pour le nom de domaine du courriel requis pour pouvoir s'inscrire, si l'on oublie la majuscule (alors qu'il ne devrait pas y en avoir dans une adresse de courriel), le bouton pour s'enregistrer ne s'active pas.
Par exemple, il faut saisir xxxxxx@Ac-montpellier.fr avec un A majuscule pour que ça fonctionne : 
![Sélection_114](https://user-images.githubusercontent.com/1470067/168279875-ad871968-1839-4468-81b2-7d01176dd7c0.png)
Cordialement,

Thierry Munoz

**Comment by garronej** [comment]
@ThierryM,  
Merci beaucoup d'avoir fait remonter, je corrige!

**Comment by garronej** [comment]
Voilà c'est corrigé!
<img width="373" alt="image" src="https://user-images.githubusercontent.com/6702424/168283138-a0eaecd8-9e97-45a7-aaa8-f1efe29c193e.png">

**Comment by ThierryM** [comment]
@garronej,
Réactivité impeccable !
Merci.
