### ISSUE TITLE
Fix date and author in LICENSE

### ISSUE THREAD

**Issue by bzg** [etalab/sill#1]
Date should be 2022 and the author should be DINUM.

**Comment by garronej** [comment]
Sure,  
Again, everything have been automatically generated by [TS-CI](https://github.com/garronej/ts-ci)

**Comment by bzg** [comment]
Sorry to reopen this: why the `EPL-2.0`?  I would expect a MIT license. The reson I use the EPL for Clojure(script) code is that it is the most commonly used license in this ecosystem, but for your code, I think MIT is okay.  Let me know if I miss something.
