### ISSUE TITLE
Fournir une documentation complète

### ISSUE THREAD

**Issue by bzg** [etalab/sill#2]
Expliquer à toute personne voulant déployer une application similaire à celle déployée sur sill.etalab.gouv.fr comment faire.

Envisager le cas où elle souhaite le faire via GitHub et celui où elle souhaite le faire via d'autres plateformes: quelles seraient les parties de configuration (voire de code) à modifier?

**Comment by bzg** [comment]
PS: idéalement, nous pourrons ajouter un fichier `publiccode.yml` dans ce méta-dépôt pour faciliter la réutilisation de l'application SILL par d'autres, et valoriser l'application dans `code.gouv.fr` quand nous y listerons les données des `publiccode.yml`.

**Comment by bzg** [comment]
J'imagine que la parties dans `docs/` est en _work in progress_ (avec pas mal d'occurrences à Onyxia), il faudrait juste le préciser dans le README au cas où (ou mettre le WIP dans une branche.)

**Comment by garronej** [comment]
D'ici ce soir.  
J'avais du mettre tout en pause quand je me suis aperçu que ce n'était pas vraiment possible de l'instancier ailleurs que dans github pour refacturer.  
Là j'avance sur la doc et je la mets en avant.

**Comment by bzg** [comment]
Merci pour le travail sur la documentation !  Je propose de considérer la version actuelle comme "complète" et d'avancer sur les issues suivantes.  Je ferme cette issue.
