### ISSUE TITLE
README: Briefly explain the problem and the proposed solution

### ISSUE THREAD

**Issue by bzg** [etalab/sill#3]
The README should briefly expose _what_ the problem is and _how_ this repository contributes to solving it.

**Comment by garronej** [comment]
I will do

**Comment by bzg** [comment]
Thanks! Doing this is not as easy as it seems, but that's even more a reason for why we shall do it as early as possible.

**Comment by garronej** [comment]
I think the "as early as possible" approach is debatable.  
I have often felt that my early documentation was dragging me back.  Vision and design choice evolve very quickly in the first weeks. 
In my experience it's best to wait that the dust settles a little bit.  
Anyway be sure that I will take great care to redact a good README in the near future.

**Comment by bzg** [comment]
Joseph Garrone ***@***.***> writes:

> I think the "as early as possible" approach is debatable.
> I have often felt that my early documentation was dragging me back.

Maybe I was not clear: this is not really documentation, it is a concise statement of what the problem is and how the repo contributes to solving it.  This is the value proposition and should probably fit into one or two sentences.

I believe this is never too early for this: the value proposition can evolve, that's okay, but the README should stay as close as what the value proposition is when we hack.

> Anyway be sure that I will take great care to redact a good README in
> the near future.

No doubt!

**Comment by bzg** [comment]
Hi @garronej - sorry to nitpick again here, I still think it's not obvious what are the problems we tackle here. I would express them like this:

> Private and public data about software in the SILL catalog come from scattered sources: from the original SILL csv file, from the sill-referent.csv file in a private repo, from Wikidata, etc.   This repository solves this by aggregating the sources, exposing them as a unique and private .json file.
> 
> Another problem is that the SILL updates are shared informally on a private mailing list, forcing the maintainer of the sill.csv file to centralize updates: this repository prepares a process that will be handled through a web interface where contributors will be able to update their own SILL entries by themselves.
> 

How does that sound?  Don't hesitate to adapt/correct if this is not the right picture - at least this reflects what I understood so far.
