### ISSUE TITLE
Ne pas inclure la présentation du SILL

### ISSUE THREAD

**Issue by bzg** [etalab/sill#4]
Voici quelques arguments:

- Il faut qu'on distingue le produit (ton code pour une application de catalogage de logiciels libres) et son implémentation (le SILL pour l'administration française): cette présentation concerne l'implémentation (avec les conventions sur qui peut ajouter quoi, etc.), pas le produit directement.
- Cette présentation est importée de https://man.sr.ht/~etalab/logiciels-libres/sill.md: l'avoir sur ce dépôt aussi obligerait à garder synchro les deux dépôts.
- La présentation est en français alors que le reste est en anglais.

Si tu es d'accord, je peux proposer une PR.

**Comment by garronej** [comment]
Oui ok je suis d'accord.  
Je me rendez bien compte qu'elle etais un peut hors sol sur la documentation technique mais c'etais pour que les lécteurs ait une experience de lécture plus agréable.  
Agathe m'avais fait remarquer que ce n'etais pas optimal de rediriger les gens sur sourcehut.  

je l'ai supprimer.

**Comment by garronej** [comment]
Je render maintenant le Markdown de sourcehut directement dans la web APP (il faudrais activer CORS sur sur SourceHut, je ne sais pas comment on fait mais toi tu dois savoir, on en discute)  

<img width="2056" alt="image" src="https://user-images.githubusercontent.com/6702424/190924888-9a10fa82-706b-48bc-bd05-871115f28dd2.png">

**Comment by bzg** [comment]
> Agathe m'avais fait remarquer que ce n'etais pas optimal de rediriger les gens sur sourcehut.

Je suis d'accord que ce n'est pas optimal - à terme, les contenus du wiki de SourceHut pourront migrer sur code.gouv.fr.

**Comment by bzg** [comment]
Je n'ai pas trouvé le lien dans https://sill.etalab.gouv.fr - je réouvre tant que ce n'est pas en prod?

(Je ne pense pas pouvoir activer CORS sur SourceHut.)

**Comment by garronej** [comment]
Ah c'est Sébastien Lorber qui présente, c'est mon premier contacte avec React :)

**Comment by garronej** [comment]
> ce n'est pas en prod?  
J'avais oublier de bumper le numéro de version, c'est en prod maintenant.  

> (Je ne pense pas pouvoir activer CORS sur SourceHut.)  

Mais c'e n'es pas possible d'activer un equivalent de GitHub pages?   

J'aimerais bien pouvoir décommenter cette ligne et commenter celle du dessus:  

https://github.com/etalab/sill-web/blob/f1565c88182af27b80e886c780cfcdf88d2dd082/src/ui/components/pages/Readme.tsx#L10

**Comment by bzg** [comment]
Je ne sais pas répondre pour l'instant - ce n'est pas prioritaire, je propose qu'on réfléchisse à une mise en ligne cohérente de la documentation des produits du pôle (incluant le SILL) quand on publiera aussi la liste de ces produits.
