### ISSUE TITLE
Keep a more useful CHANGELOG.md

### ISSUE THREAD

**Issue by bzg** [etalab/sill#4]
The current `CHANGELOG.md` is cryptic: what is "update" and what is "bin"?

We don't necessary need to keep a changelog for `x.x.X` versions, at least not until such versions come with a set of issues fixed, in which case, a link to the issue in the changelog would do.

But let's take a habit of keeping a useful changelog for `x.X` future versions.

(Also, why no `0.0.4` version?)

**Comment by garronej** [comment]
Hi @bzg,  
The README is not keep up to date by myself but a bot is tracking my commit message between version releases and generating this README automatically.  
It's also a feature of [TS-CI](https://github.com/garronej/ts-ci)

Be sure that I will take care to come up with meaning-full commit messages in the future but for now, everything is moving sand.  I am just setting things up. 

> (Also, why no 0.0.4 version?)

The version are published automatically when I bump the [version](https://github.com/etalab/sill/blob/120f0384b162a4f4554aa5b92017a1c0d5436b4e/package.json#L3). I must have bump it twice and not push in between.

**Comment by bzg** [comment]
The benefit of a changelog file is that it is _readable_ and provide useful information between versions.  Otherwise people could simply read the commit messages.  Sometimes writing/editing it by hand helps.

If the changelog is autogenerated, fine.  And I know the repo is still also.  My point was that, at least for future minor version (x.[0-9].x) we shall have something meaningful to read when we receive (like I did) a notification that there is a new release.

(For the skipped `0.0.4`, perhaps your bot could take care of detecting all tags, including when there are more than one in the commits series that you push? Just a thought.)

**Comment by garronej** [comment]
> The benefit of a change log file is that it is readable and provide useful information between versions. Otherwise people 
> could simply read the commit messages. Sometimes writing/editing it by hand helps.  

Yes agreed.  
It's useful though to start from an automatically generated base.  
Every commit that contains the word "changelog" is ignored.  
This is why I often put things like "Bump version (changelog ignore)" as commit message.  

> like I did  

Good points, there are automatically 6 watchers on the repo. 
I will disable GitHub releasing for now. I need to release because the CI is pulling the NPM package but I don't want to attract the attention of anyone yet.

**Comment by bzg** [comment]
Joseph Garrone ***@***.***> writes:

> This is why I often put things like "Bump version (changelog ignore)" as commit message.

But then using your bot forces you to clutter the commit messages with information that is only relevant if you know there is a bot :/

> I will disable GitHub releasing for now. I need to release because the CI is pulling the NPM package but I don't want to attract the attention of anyone yet.

Don't worry about people's attention yet, people can unsubscribe if they want.

I'm concerned with setting up good practices from the start for anything related to the projec's _communication_ (like useful commit messages, useful release messages, a useful changelog, etc.)

What matters right now is that things move in the right direction :)
