### ISSUE TITLE
Retirer la syntaxe propre à GitBook

### ISSUE THREAD

**Issue by bzg** [etalab/sill#5]
Nous ne pouvons pas utiliser GitBook pour cette documentation sans décider de l'outil qu'on utilisera pour l'ensemble des documentations des produits du pôle logiciels libres.

Avoir la documentation d'un produit en markdown dans GitHub est habituel et assez lisible: je propose qu'on reste sur GitHub pour cette documentation, en attendant de savoir où nous publierons l'ensemble des documentations des produits du pôle logiciels libres.

**Comment by garronej** [comment]
Ok je comprend.  
J'ai fait en sorte que les Markdown soit consultable facilement sans avoir besoin de passer par gitbook.  
J'ai renommer les fichier et déplacer tout a la racine.  
Nous pouvons migrer vers un génrateur de site statique libre quand tu veut.  

Je pense que https://docusaurus.io/ c'est bien.

**Comment by bzg** [comment]
> Je pense que https://docusaurus.io/ c'est bien.

D'ac.  Attendons quand même la démo Docusaurus lors de l'atelier BlueHats du 14 octobre ;)

**Comment by garronej** [comment]
Ah c'est Sébastien Lorber qui présente, c'est mon premier contacte avec React :)

**Comment by bzg** [comment]
> Je pense que https://docusaurus.io/ c'est bien.

D'ac.  Attendons quand même la démo Docusaurus du [14 octobre](https://github.com/blue-hats/ateliers/blob/main/ateliers.org#14-octobre--pr%C3%A9sentation-de-docusaurus) ;)
