### ISSUE TITLE
The README should contain a license section

### ISSUE THREAD

**Issue by bzg** [etalab/sill#5]
See https://git.sr.ht/~etalab/code.gouv.fr#licenses for example.

**Comment by garronej** [comment]
I will use the correct licence but, please keep in mind that everything in this repo that you criticise have been automatically setup by [TS-CI](https://github.com/garronej/ts-ci) and not wrote by me explicitly.  

About putting it in the `README`.  I will comply although I don't think it's necessary considering the widely common and accepted practice is to put a `LICENCE` file at the root of the repo.

![image](https://user-images.githubusercontent.com/6702424/151693341-4a5c30a8-66a9-456d-9fb2-5c9d8a4cf2de.png)

It's directly clickable in the about section

![image](https://user-images.githubusercontent.com/6702424/151693329-137d90d4-6693-45cc-bafd-b138f5032fdc.png)

And it's in the `package.json`

![image](https://user-images.githubusercontent.com/6702424/151693746-6adb7223-7266-4ee8-88a7-61a1e272080b.png)

**Comment by bzg** [comment]
About the license, this is not "criticism", just a reminder.

About mentioning the author and license in a dedicated section in the README, I won't dispute what is common practice, since this is hard to assess.  (Authoritative GNU repositories always mention the author and license in the README.)

Adding such a section is what _we_ should recommend for all public sector repositories since it clearly gives a useful information for the users.

GitHub has its own way of recognizing licenses and making it more obvious for the users, but not all repositories are on GitHub.

**Comment by garronej** [comment]
Where there is more than one license that apply on a repo it's true that some extra indication in the reader about what applies to what is a good thing.

**Comment by bzg** [comment]
Well, I think this is _always_ a good thing and that READMEs should follow the conventions set by the GNU project, which was the first to set the standard here.
