### ISSUE TITLE
Indiquer quel est le problème résolu par cette application

### ISSUE THREAD

**Issue by bzg** [etalab/sill#6]
Cette documentation vise les personnes ou institutions qui voudraient mettre en place un catalogue de logiciels libres.

Cela peut être, par exemple, un Open Source Program Office d'un autre pays.

Il faudrait un paragraphe introductif motivant le fait de développer cette application: quel est le problème qu'elle permet de résoudre?

Plus précisément, il faut expliquer le passage de l'ancien système (un csv dans un dépôt GitHub + un frontend qui l'expose) à ce système (une base de données dans un dépôt + une webapp avec authentification qui permet d'éditer la base et d'exposer les logiciels).

Si un jour l'application devient assez générique, elle sera une application de catalogage de logiciels (libres) qu'on pourra comparer à d'autres solutions, ce sera important d'aider les réutilisateurs potentiels à comprendre pourquoi choisir celle-ci, en fonction de leurs contraintes.

**Comment by garronej** [comment]
Ok!   
Je met cette issue dans sill-web et je l'ajouter a une milestone

**Comment by garronej** [comment]
https://github.com/etalab/sill-web/issues/104
