### ISSUE TITLE
Ne pas recommander d'utiliser VS Code

### ISSUE THREAD

**Issue by bzg** [etalab/sill#7]
Attention à ne pas faire des recommandations qui vont à l'encontre des recommandations du SILL... surtout dans la documentation du SILL.

L'idéal serait de pouvoir donner des indications sur l'usage des éditeurs de texte présents dans le SILL - je ne sais pas si la recommandation actuelle est aussi valable pour VSCodium, mais j'imagine que oui.

**Comment by garronej** [comment]
Ah oui bien sûr 😣
Je vais corriger ça!

**Comment by garronej** [comment]
En fait je croyais l'avoir supprimé...

**Comment by garronej** [comment]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/6702424/190910999-decfda92-fa65-43d1-9b95-d1563731449a.png">
